### ISSUE TITLE
Navigation disjointed

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/ov-frontend#107]
### Description

When I go to the cooking collection, the related contents and credits anchors in the navigation on left side are spaced lower than the other anchors

### Reproduction steps

1. Go to  https://ov.wgbh-mla.org/collections/cooking
2. Scroll to find the two anchors, separated from other anchors

### Expected behavior

All navigation links/anchors should be groups together at the top of the page.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

**Comment by foglabs** [comment]
took a look: this collection was created with 'text' content blocks as titles between AAPBRecord blocks corresponding to different shows, but because each AAPBRecord blocks' title field is blank, the AAPBRecords are showing blank in the sidebar. the 'text' blocks should be deleted, with each title text moved into the title field for the corresponding AAPBRecord block.

**Comment by ekemeyer** [comment]
can be fixed on user side of wag tail, not an ov-frontend issue.
