### ISSUE TITLE
Provide Start/End Time For AAPB Content Blocks

### ISSUE THREAD

**Issue by phigg** [WGBH-MLA/ov-frontend#46]
Back in December we discussed the possibility of using a new "lite" embed to show a video player without displaying AAPB metadata. My notes at the time said some tweaking would be needed before that would work, but nothing more. 

- Are lite embeds sufficiently tweaked to be used in HTML content blocks?
- Will lite embeds allow the share a segment feature as show in the classic embed below?

`<iframe style='display: flex; flex-direction: column; min-height: 150vh; width: 100%;' src='https://americanarchive.org/embed/cpb-aacip-15-54kkwx56?start=257.79&end=383.47'></iframe>`

**Comment by foglabs** [comment]
the lite embed option from AAPB was originally intended for embedding on OV redesign, but we ended up making a third openvault-specific embed option that OV redesign uses in order to follow creative's design. so, is the idea here to switch OVR to the 'lite' embed option (no color ORR overlay, more gray), or is this just following up on the original video player design work? I don't think the current OVR embed option shows AAPB metadata beyond the title.

thanks peter!

**Comment by phigg** [comment]
@foglabs as we discussed, using one of the existing content blocks that take GUIDs (Programs, Interviews, etc.) could work, provided they were able to accept start point and end points to embed just the segment referred to in the exhibit text. 

I was thinking about using an HTML content block to use the iframe info as shown above, but whatever way it works is fine with me.

it might make the most sense to create an additional content block for Segments that allows entry of start and end times.

**Comment by foglabs** [comment]
@phigg thanks peter! changed the title based on our discussion - for posterity, we determined that we just need to add start/end time support to AAPB content blocks to allow particular segments of a record to be shown in an OVR video player
